# grub-menu.sh — script body for the writeShellApplication wrapper in
# grub-menu.nix, which supplies the bash shebang, the
# `set -o errexit/nounset/pipefail` preamble, and the store PATH, so this file
# has neither.  Run it standalone with `bash grub-menu.sh ...` if needed.
#
# Minimal reimplementation of install-grub.pl's core flow:
#   generate grub.cfg entries for the current generation and every historical
#   generation found in the NixOS profile directories, install each entry's
#   kernel and initrd into the boot directory, write the config atomically.
# Nothing else: no themes/fonts/splash, no users/passwords, no os-prober,
# no extra* hooks, no initrd secrets, no zfs handling, no grub-install.
#
# Usage: grub-menu.sh <toplevel>
#   toplevel  system.build.toplevel of the new configuration
# Environment (so it can be tested without root):
#   BOOT      boot directory      (default /boot)
#   LIMIT     max generations shown (default 100)
#   STORE     store root          (default /nix/store)
#   PROFILES  profile root        (default /nix/var/nix/profiles)
# Kernel/initrd installation into $BOOT/kernels is mandatory (always copied).
# Needs: bash 4.4+, findmnt (util-linux), coreutils.
shopt -s nullglob

readonly toplevel=$1                        # like $ARGV[1] in install-grub.pl
readonly boot=${BOOT:-/boot}
readonly limit=${LIMIT:-100}
readonly store=${STORE:-/nix/store}
readonly profiles=${PROFILES:-/nix/var/nix/profiles}
readonly distro=NixOS

conf=""; declare -A copied=()               # grub.cfg under construction; kernels placed this run
emit() { conf+="$1"$'\n'; }

# --- Filesystem discovery (GrubFs): how GRUB must refer to $boot --------------
mkdir -p "$boot/grub" "$boot/kernels"
chmod 700 "$boot/grub" || true
boot_mnt=$(findmnt -no TARGET --target "$boot")   # innermost mount point covering $boot
boot_fsroot=$(findmnt -no FSROOT --target "$boot") # that mount's root within its filesystem:
                                                  # "/" normally, or the subvolume path (e.g.
                                                  # "/boot") when $boot is mounted out of a
                                                  # btrfs subvolume of a bigger filesystem
boot_rel=${boot_fsroot%/}${boot#"$boot_mnt"}      # path from the filesystem root to $boot, since
                                                  # GRUB's drivers address the filesystem root,
                                                  # not the mounted subvolume ("" only when $boot
                                                  # is the fs root itself)
boot_prefix=""                                             # how entries prefix paths under $boot
boot_uuid=$(findmnt -no UUID --target "$boot")
boot_label=$(findmnt -no LABEL --target "$boot")
emit "# Automatically generated.  DO NOT EDIT THIS FILE!"
if [ -n "$boot_uuid" ]; then
    emit "search --no-floppy --fs-uuid --set=drive1 $boot_uuid"; boot_prefix="(\$drive1)"
elif [ -n "$boot_label" ]; then                            # e.g. some FAT/ext setups
    emit "search --no-floppy --fs-label --set=drive1 $boot_label"; boot_prefix="(\$drive1)"
else                                                       # e.g. tmpfs: fall back to plain paths
    echo "warning: $boot has no UUID/LABEL, entries use plain paths" >&2
fi
emit ""
emit "set default=0"
emit "set timeout=5"
emit ""

# --- copyToKernelsDir: install a kernel/initrd under $boot, return GRUB path --
kpath() { # $1 = path in the store; result in $grub_path
    local src=$1 name dst
    name=${src#"$store"}; name=${name//\//-}; name=${name#-}   # flatten to one filename
    dst=$boot/kernels/$name
    if [ ! -e "$dst" ]; then               # copy via .tmp + rename: never leave a half file
        cp -- "$src" "$dst.tmp"
        mv -- "$dst.tmp" "$dst"
    fi
    copied[$dst]=1
    grub_path="$boot_prefix$boot_rel/kernels/$name"
}

# --- addEntry: one menuentry for the system living at $2 ----------------------
add_entry() { # $1 = label, $2 = system toplevel
    local name=$1 path=$2 kernel initrd params
    [ -e "$path/kernel" ] && [ -e "$path/initrd" ] || return 0   # garbage-collected
    kpath "$(readlink -f "$path/kernel")"; kernel=$grub_path
    kpath "$(readlink -f "$path/initrd")"; initrd=$grub_path
    params="init=$(readlink -f "$path/init") $(cat "$path/kernel-params" 2>/dev/null || true)"
    emit "menuentry \"$name\" {"
    emit "  linux $kernel $params"
    emit "  initrd $initrd"
    emit "}"
    emit ""
}

# --- addGeneration: the system at $path plus its specialisations --------------
add_generation() { # $1 = label, $2 = path, $3 = 1 when this is the current generation
    local label=$1 path=$2 current=$3 spec name
    local specs=("$path"/specialisation/*)

    # Older generations that have specialisations become a submenu;
    # the current generation stays flat at the top level.
    local wrap=$(( ${#specs[@]} > 0 && current == 0 ))
    local deflabel=$label
    if (( ${#specs[@]} > 0 )); then deflabel="$label - Default"; fi
    if (( wrap )); then emit "submenu \"$label\" --class submenu {"; fi

    add_entry "$deflabel" "$path"
    for spec in "${specs[@]}"; do
        name=$(cat "$spec/configuration-name" 2>/dev/null || true)
        [ -n "$name" ] || name="(${spec##*/} - $(date -r "$spec" +%F))"
        add_entry "$label - $name" "$spec"
    done

    if (( wrap )); then emit "}"; fi
}

# --- addProfile: one submenu per generation symlink of a NixOS profile --------
add_profile() { # $1 = profile base, $2 = submenu title
    local base=$1 title=$2 gen link count=0 ver
    emit "submenu \"$title\" --class submenu {"
    while read -r gen link; do
        (( ++count > limit )) && break
        ver=$(cat "$link/nixos-version" 2>/dev/null || true)
        [ -n "$ver" ] || { echo "skipping corrupt generation $link" >&2; continue; }
        add_generation "$distro - Configuration $gen ($(date -r "$link" +%F) - $ver)" "$link" 0
    done < <(for link in "$base"-*-link; do
                 [[ $link =~ -([0-9]+)-link$ ]] && echo "${BASH_REMATCH[1]} $link"
             done | sort -rn)                 # newest generation first
    emit "}"
    emit ""
}

# --- Menu assembly, in install-grub.pl's order --------------------------------
add_generation "$distro" "$toplevel" 1
add_profile "$profiles/system" "$distro - All configurations"
for profile in "$profiles"/system-profiles/*; do
    name=${profile##*/}
    if [[ $name =~ ^[[:alnum:]_]+$ ]]; then
        add_profile "$profile" "$distro - Profile '$name'"
    fi
done

# --- Atomically install the config, then forget unreferenced kernels ----------
tmp=$boot/grub/grub.cfg.tmp
printf '%s' "$conf" > "$tmp"
mv -- "$tmp" "$boot/grub/grub.cfg"

for fn in "$boot"/kernels/*; do
    [[ -n ${copied[$fn]:-} ]] || { echo "removing obsolete $fn" >&2; rm -f -- "$fn"; }
done

echo "wrote $boot/grub/grub.cfg"
