name: "build"
on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      commit:
        description: 'nixpkgs commit'
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v5
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v16
      with:
        name: klozher
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: |
        if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
          nix flake lock --override-input nixpkgs github:NixOS/nixpkgs/${{ github.event.inputs.commit }}
        fi
        nix flake show --json | jq  '.packages."aarch64-linux"|keys[]'| xargs -I {} nix build -L .#{}

