name: Debug on x86-64
on: [workflow_dispatch]
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v31
    - uses: cachix/cachix-action@v17
      with:
        name: klozher
        authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true # Restrict to the user who triggered the workflow
        wait-timeout-minutes: 5
    - name: Archive code coverage results
      uses: actions/upload-artifact@v7
      with:
        name: outputs
        path: /home/runner/outputs
        if-no-files-found: ignore
