name: Debug on aarch64
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: cachix/install-nix-action@v31
    - name: Setup upterm session
      uses: owenthereal/action-upterm@v1
      with:
        limit-access-to-actor: true # Restrict to the user who triggered the workflow
        wait-timeout-minutes: 5

