name: Auto Update Flake

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:
  update-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Update flake.lock
        run: nix flake update

      - name: Upload updated lockfile
        uses: actions/upload-artifact@v7
        with:
          name: updated-flake-lock
          path: flake.lock

  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - hostname: "gurren"
            os: "ubuntu-24.04"
          - hostname: "pipa"
            os: "ubuntu-24.04-arm"
          - hostname: "giga"
            os: "ubuntu-24.04"
          - hostname: "lagann"
            os: "ubuntu-24.04"

    needs: update-lock
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Upload to cachix
        uses: cachix/cachix-action@v17
        with:
          name: klozher
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Build current flake
        run: nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel --show-trace

      - name: Download updated lockfile
        uses: actions/download-artifact@v8
        with:
          name: updated-flake-lock

      - name: Build updated flake
        run: nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel --show-trace

  push-inputs:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download updated lockfile
        uses: actions/download-artifact@v8
        with:
          name: updated-flake-lock

      - name: Install nix
        uses: cachix/install-nix-action@v31

      - name: Install cachix
        uses: cachix/cachix-action@v17
        with:
          name: klozher
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: ""

      - name: Fetch input sources
        run: nix flake prefetch-inputs

      - name: Push input sources
        run: cachix push klozher /nix/store/*-source
        env:
          CACHIX_AUTH_TOKEN: "${{ secrets.CACHIX_AUTH_TOKEN }}"

  create-pr:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Download updated lockfile
        uses: actions/download-artifact@v8
        with:
          name: updated-flake-lock

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          branch: "auto-update-flake"
          commit-message: "chore: auto update flake.lock (all hosts validated)"
          title: "chore: auto update flake.lock"
          body: |
            This is an automated PR to update `flake.lock`.
            All hosts builds passed successfully.
